artifact_uri: file:C:\Users\Paola Andrea\Documentos\ProductoDatos\2025-1-productos-de-datos\PRE-08-mlflow-tracking-local-Paolabustos0510\my_mlruns/368409997155474044/e86df78b019740c3bb8fb3cc1f9e7c1f/artifacts
end_time: 1748304015877
entry_point_name: ''
experiment_id: '368409997155474044'
lifecycle_stage: active
run_id: e86df78b019740c3bb8fb3cc1f9e7c1f
run_name: knn_863d2b65
run_uuid: e86df78b019740c3bb8fb3cc1f9e7c1f
source_name: ''
source_type: 4
source_version: ''
start_time: 1748304015775
status: 3
tags: []
user_id: Paola Andrea
