artifact_uri: file:C:\Users\Paola Andrea\Documentos\ProductoDatos\2025-1-productos-de-datos\PRE-08-mlflow-tracking-local-Paolabustos0510\my_mlruns/368409997155474044/af818ba6e1bd490c9afa7240f34c1c10/artifacts
end_time: 1748302673162
entry_point_name: ''
experiment_id: '368409997155474044'
lifecycle_stage: active
run_id: af818ba6e1bd490c9afa7240f34c1c10
run_name: knn_7fe282a7
run_uuid: af818ba6e1bd490c9afa7240f34c1c10
source_name: ''
source_type: 4
source_version: ''
start_time: 1748302673050
status: 3
tags: []
user_id: Paola Andrea
