artifact_uri: file:C:\Users\Paola Andrea\Documentos\ProductoDatos\2025-1-productos-de-datos\PRE-08-mlflow-tracking-local-Paolabustos0510\my_mlruns/368409997155474044/88e96a04e9fb4f0f844af992fc7b0d0a/artifacts
end_time: 1748480276265
entry_point_name: ''
experiment_id: '368409997155474044'
lifecycle_stage: active
run_id: 88e96a04e9fb4f0f844af992fc7b0d0a
run_name: knn_22f3a23b
run_uuid: 88e96a04e9fb4f0f844af992fc7b0d0a
source_name: ''
source_type: 4
source_version: ''
start_time: 1748480276177
status: 3
tags: []
user_id: Paola Andrea
