artifact_uri: file:C:\Users\Paola Andrea\Documentos\ProductoDatos\2025-1-productos-de-datos\PRE-08-mlflow-tracking-local-Paolabustos0510\my_mlruns/368409997155474044/ff475cd6b8c543f09abd2e4fd1e9a20d/artifacts
end_time: 1748301521461
entry_point_name: ''
experiment_id: '368409997155474044'
lifecycle_stage: active
run_id: ff475cd6b8c543f09abd2e4fd1e9a20d
run_name: knn_bad8684b
run_uuid: ff475cd6b8c543f09abd2e4fd1e9a20d
source_name: ''
source_type: 4
source_version: ''
start_time: 1748301521374
status: 3
tags: []
user_id: Paola Andrea
