artifact_uri: file:C:\Users\Paola Andrea\Documentos\ProductoDatos\2025-1-productos-de-datos\PRE-08-mlflow-tracking-local-Paolabustos0510\my_mlruns/368409997155474044/b6db045ed27c42c78d0cfeca288d375e/artifacts
end_time: 1748302055642
entry_point_name: ''
experiment_id: '368409997155474044'
lifecycle_stage: active
run_id: b6db045ed27c42c78d0cfeca288d375e
run_name: knn_23f927ac
run_uuid: b6db045ed27c42c78d0cfeca288d375e
source_name: ''
source_type: 4
source_version: ''
start_time: 1748302055530
status: 3
tags: []
user_id: Paola Andrea
